// Code generated by re2dfa (https://github.com/opennota/re2dfa). DO NOT EDIT
// re2dfa -o address_re2dfa_xpub.go "^xpub[a-km-zA-HJ-NP-Z0-9]{107,108}$" blockchain.validateBitcoinXpub string

package blockchain

import "unicode/utf8"

func validateBitcoinXpub(s string) (end int) {
	end = -1
	var r rune
	var rlen int
	i := 0
	_, _, _ = r, rlen, i
	switch {
	case i == 0:
		goto s2
	}
	return
s2:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r == 120:
		goto s3
	}
	return
s3:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r == 112:
		goto s4
	}
	return
s4:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r == 117:
		goto s5
	}
	return
s5:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r == 98:
		goto s6
	}
	return
s6:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s7
	}
	return
s7:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s8
	}
	return
s8:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s9
	}
	return
s9:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s10
	}
	return
s10:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s11
	}
	return
s11:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s12
	}
	return
s12:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s13
	}
	return
s13:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s14
	}
	return
s14:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s15
	}
	return
s15:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s16
	}
	return
s16:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s17
	}
	return
s17:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s18
	}
	return
s18:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s19
	}
	return
s19:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s20
	}
	return
s20:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s21
	}
	return
s21:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s22
	}
	return
s22:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s23
	}
	return
s23:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s24
	}
	return
s24:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s25
	}
	return
s25:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s26
	}
	return
s26:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s27
	}
	return
s27:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s28
	}
	return
s28:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s29
	}
	return
s29:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s30
	}
	return
s30:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s31
	}
	return
s31:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s32
	}
	return
s32:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s33
	}
	return
s33:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s34
	}
	return
s34:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s35
	}
	return
s35:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s36
	}
	return
s36:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s37
	}
	return
s37:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s38
	}
	return
s38:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s39
	}
	return
s39:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s40
	}
	return
s40:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s41
	}
	return
s41:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s42
	}
	return
s42:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s43
	}
	return
s43:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s44
	}
	return
s44:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s45
	}
	return
s45:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s46
	}
	return
s46:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s47
	}
	return
s47:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s48
	}
	return
s48:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s49
	}
	return
s49:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s50
	}
	return
s50:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s51
	}
	return
s51:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s52
	}
	return
s52:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s53
	}
	return
s53:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s54
	}
	return
s54:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s55
	}
	return
s55:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s56
	}
	return
s56:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s57
	}
	return
s57:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s58
	}
	return
s58:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s59
	}
	return
s59:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s60
	}
	return
s60:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s61
	}
	return
s61:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s62
	}
	return
s62:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s63
	}
	return
s63:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s64
	}
	return
s64:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s65
	}
	return
s65:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s66
	}
	return
s66:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s67
	}
	return
s67:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s68
	}
	return
s68:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s69
	}
	return
s69:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s70
	}
	return
s70:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s71
	}
	return
s71:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s72
	}
	return
s72:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s73
	}
	return
s73:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s74
	}
	return
s74:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s75
	}
	return
s75:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s76
	}
	return
s76:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s77
	}
	return
s77:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s78
	}
	return
s78:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s79
	}
	return
s79:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s80
	}
	return
s80:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s81
	}
	return
s81:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s82
	}
	return
s82:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s83
	}
	return
s83:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s84
	}
	return
s84:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s85
	}
	return
s85:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s86
	}
	return
s86:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s87
	}
	return
s87:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s88
	}
	return
s88:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s89
	}
	return
s89:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s90
	}
	return
s90:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s91
	}
	return
s91:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s92
	}
	return
s92:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s93
	}
	return
s93:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s94
	}
	return
s94:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s95
	}
	return
s95:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s96
	}
	return
s96:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s97
	}
	return
s97:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s98
	}
	return
s98:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s99
	}
	return
s99:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s100
	}
	return
s100:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s101
	}
	return
s101:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s102
	}
	return
s102:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s103
	}
	return
s103:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s104
	}
	return
s104:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s105
	}
	return
s105:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s106
	}
	return
s106:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s107
	}
	return
s107:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s108
	}
	return
s108:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s109
	}
	return
s109:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s110
	}
	return
s110:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s111
	}
	return
s111:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s112
	}
	return
s112:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s113
	}
	return
s113:
	switch {
	case i == len(s):
		end = i
		return
	}
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r >= 48 && r <= 57 || r >= 65 && r <= 72 || r >= 74 && r <= 78 || r >= 80 && r <= 90 || r >= 97 && r <= 107 || r >= 109 && r <= 122:
		goto s115
	}
	return
s115:
	switch {
	case i == len(s):
		end = i
	}
	return
}
